apiVersion: v2
name: grafana-operator
description: Grafana Operator for Kubernetes
type: application
version: 1.0.0
appVersion: "v5.20.0"

dependencies:
  - name: grafana-operator
    repository: https://grafana.github.io/helm-charts
    version: "v5.20.0"
