apiVersion: v2
name: k8s-infra
description: SigNoz K8s-Infra for collecting metrics and logs
type: application
version: 1.0.0
appVersion: "0.139.0"

dependencies:
  - name: k8s-infra
    repository: https://charts.signoz.io
    version: "0.15.0"
