k8s-infra:
  global:
    cloud: other
    clusterName: xquare-onpremise
    deploymentEnvironment: production

  otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
  otelInsecure: true

  presets:
    otlpExporter:
      enabled: true
    loggingExporter:
      enabled: true
