apiVersion: v2
name: longhorn
description: longhorn chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.11.0"
dependencies:
  - name: longhorn
    version: "1.11.0"
    repository: "https://charts.longhorn.io"
