apiVersion: v2
name: harbor
description: harbor chart for Kubernetes
type: application
version: 1.0.0
appVersion: "2.12.0"
dependencies:
  - name: harbor
    version: 1.18.2
    repository: "https://helm.goharbor.io"
