apiVersion: v2
name: opentelemetry-operator
description: OpenTelemetry Operator for Kubernetes
type: application
version: 1.0.0
appVersion: "0.138.0"

dependencies:
  - name: opentelemetry-operator
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.105.0
