apiVersion: v2
name: vault
description: vault chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.18.1"
dependencies:
  - name: vault
    version: 1.2.0
    repository: "https://helm.releases.hashicorp.com"
