apiVersion: v1
kind: Service
metadata:
  name: buildkit
  namespace: {{ .Values.namespace }}
  labels:
    app: buildkit
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 1234
    protocol: TCP
    name: buildkit
  selector:
    app: buildkit
