apiVersion: v2
name: victoria-metrics-operator
description: VictoriaMetrics Operator
type: application
version: 1.0.0
appVersion: "v0.65.0"

dependencies:
  - name: victoria-metrics-operator
    repository: https://victoriametrics.github.io/helm-charts/
    version: "0.56.4"
