image:
  repository: moby/buildkit
  tag: v0.27.1
  pullPolicy: IfNotPresent

namespace: buildkit

replicas: 1

deployment:
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  port: 1234

buildkit:
  debug: false
  rootDir: /var/lib/buildkit
  extraArgs:
    - --oci-worker-gc=true
    - --oci-worker-gc-keepstorage=10000,10000,190000

storage:
  pvc:
    enabled: true
    storageClass: longhorn
    size: 200Gi

podSecurityContext: {}

securityContext:
  privileged: true

resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 500m
    memory: 2Gi

serviceAccount:
  create: true
  name: buildkit
  annotations: {}
