image:
  repository: moby/buildkit
  tag: v0.25.2
  pullPolicy: IfNotPresent

namespace: buildkit

replicas: 1

deployment:
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  port: 1234

buildkit:
  debug: false
  rootDir: /var/lib/buildkit
  extraArgs: []

storage:
  pvc:
    enabled: true
    storageClass: longhorn
    size: 200Gi

podSecurityContext: {}

securityContext:
  privileged: true

resources:
  limits:
    memory: 16Gi
  requests:
    cpu: 2
    memory: 4Gi

serviceAccount:
  create: true
  name: buildkit
  annotations: {}
