---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-vault-service-account
  namespace: harbor
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: vault-service-account
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: harbor-vault-auth
  namespace: harbor
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare-app
    serviceAccount: harbor-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v1
  mount: xquare-infra-kv
  path: harbor
  destination:
    name: harbor-admin-password
    create: true
  refreshAfter: 1h
  vaultAuthRef: harbor/harbor-vault-auth
