apiVersion: v2
name: grafana
description: Grafana dashboard for Grafana Cloud datasources
type: application
version: 1.0.0
appVersion: "11.4.0"

dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: "8.8.2"
