apiVersion: v2
name: grafana
description: Grafana dashboard for Grafana Cloud datasources
type: application
version: 1.0.0
appVersion: "12.2.1"

dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: "10.1.4"
