---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-k8s-monitoring-vault-service-account
  namespace: grafana-k8s-monitoring
  labels:
    app.kubernetes.io/name: grafana-k8s-monitoring
    app.kubernetes.io/component: vault-service-account
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: grafana-k8s-monitoring-vault-auth
  namespace: grafana-k8s-monitoring
  labels:
    app.kubernetes.io/name: grafana-k8s-monitoring
    app.kubernetes.io/component: vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare-app
    serviceAccount: grafana-k8s-monitoring-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-cloud-credentials
  namespace: grafana-k8s-monitoring
  labels:
    app.kubernetes.io/name: grafana-k8s-monitoring
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v2
  mount: xquare-infra-kv
  path: grafana-k8s-monitoring
  destination:
    name: grafana-cloud-credentials
    create: true
  refreshAfter: 1h
  vaultAuthRef: grafana-k8s-monitoring/grafana-k8s-monitoring-vault-auth
