---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-vault-service-account
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: vault-service-account
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cert-manager-vault-auth
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: vault-auth
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: xquare-app
    serviceAccount: cert-manager-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: vault-secret
spec:
  type: kv-v2
  mount: xquare-infra-kv
  path: cert-manager
  destination:
    name: cloudflare-api-token-secret
    create: true
  refreshAfter: 1h
  vaultAuthRef: cert-manager/cert-manager-vault-auth
