apiVersion: v1
name: cert-manager
version: 2.0.0
appVersion: v1.17.1
kubeVersion: ">= 1.22.0-0"
description: A Helm chart for cert-manager
home: https://github.com/cert-manager/cert-manager
dependencies:
  - name: cert-manager
    version: 1.19.3
    repository: https://charts.jetstack.io
