tenantId: "1"

replicaCount: 2

image:
  repository: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
