apiVersion: v2
name: grafana-k8s-monitoring
description: Grafana Kubernetes Monitoring Stack
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: k8s-monitoring
    version: 3.5.6
    repository: https://grafana.github.io/helm-charts
